### ISSUE TITLE
PK_NCA tab

### ISSUE THREAD

**Issue by shuyingyang-gsk** [PavanVaddady/modvizpop#2]
Hi Pavan,
I am trying your modvizpop app, very nice! Simulated data, plots tab were all looking good. But when trying to obtain the NCA results, it appeared the following error and then the app stopped: "group_cols must not overlap with standardized column names".
What's the issue here?

Many thanks,

Shuying Yang

**Comment by PavanVaddady** [comment]
Thanks Shuying. This is stemming from an update to the PKNCA package alongside other updates to relevant packages. I will update the app with the latest R packages soon. 

Pavan.
