### ISSUE TITLE
Number of subjects/IDs in the simulation data

### ISSUE THREAD

**Issue by cyangrwp** [PavanVaddady/modvizpop#3]
Hi Pavan,

I am new to Pharmacometrics and find your shiny app very helpful. Can I ask a question about the simulation part of the app?
It looks like when specifying number of subjects = 1 in the simulation options, the simulation data will have two IDs (1 and 2) when the dose is 100,200 (default), which is a bit confusing to me as I am expecting only one ID in this case. Did I miss something?

Best,
Chen

**Comment by PavanVaddady** [comment]
Hi Chen,

For each dose it is assigning a new ID. If you had only one dose it will have only one ID. Instead, if you want to have the same ID getting two doses back to back, please provide an event input file (see Help for how to provide external Event Input dataset).

**Comment by PavanVaddady** [comment]
Hi Chen,

Thanks for your feedback! For each dose it is assigning a new ID. If you had only one dose it will have only one ID. Instead, if you want to have the same ID getting two doses back to back, please provide an event input file (see Help for how to provide external Event Input dataset). 

Regards,
Pavan.
